language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-24.0.2

    - android-24

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-24
    - sys-img-x86-android-24

before_install:
 - chmod +x gradlew
